blog_page:
    resource:   Blogger\BlogBundle\Controller\PageController
    type:       annotation
            
blog_blog:
    resource:   Blogger\BlogBundle\Controller\BlogController
    type:       annotation

blog_comment:
    resource:   Blogger\BlogBundle\Controller\CommentController
    type:       annotation
